title: Blog Técnico de Furbano
description: Explorando Azure, .NET Core, Azure Functions, AKS y modernización de aplicaciones.
baseurl: "/furbano.github.io"
url: "https://freddan58.github.io"
theme: minima
plugins:
  - jekyll-feed
author:
  name: Freddy Urbano
  email: freddan58@gmail.com