title: Blog Técnico de Furbano
description: Explorando Azure, .NET Core, Azure Functions, AKS y modernización de aplicaciones.
baseurl: ""
url: "https://furbano.github.io"
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
author:
  name: Freddy Urbano
  email: freddan58@gmail.com